# Generated by Django 4.2.5 on 2023-09-17 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work_line', models.CharField(choices=[('Jeweler', 'Jeweler'), ('Beat maker', 'Beatmaker'), ('Others', 'Others')], default='Others', max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.FloatField(default=1, max_length=128)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products')),
                ('description', models.TextField(max_length=256)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('expiration', models.DateTimeField(default=None, null=True)),
                ('seller', models.ForeignKey(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seller', 'code')},
            },
        ),
    ]
