# Generated by Django 4.2.5 on 2023-10-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='quantity',
            field=models.FloatField(max_length=128),
        ),
    ]
