# Generated by Django 4.2.5 on 2023-10-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.FloatField(max_length=128),
        ),
    ]
