# Generated by Django 4.2.5 on 2023-09-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar'),
        ),
    ]
