# Generated by Django 4.2.5 on 2023-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
