# Generated by Django 4.2.5 on 2023-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='cuit',
            field=models.CharField(max_length=13),
        ),
    ]
